### ISSUE TITLE
Document supported frequencies / band in the readme

### ISSUE THREAD

**Issue by electroniceel** [sp5wwp/TR-9#1]
I saw a link to M17 and the TR-9 and it sparked my interest. Unfortunately I couldn't easily find out what kinds of frequencies / bands the TR-9 does support. I think adding this info to the README.md would improve it.

Is there also support for FM or other modes, as fallback when the remote end doesn't have M17?

**Comment by kc1awv** [comment]
PR https://github.com/M17-Project/TR-9/pull/2

will address these questions.
