### ISSUE TITLE
Split this repo

### ISSUE THREAD

**Issue by sp5wwp** [sp5wwp/TR-9#13]
Split this repo into 3:
- firmware
- case design
- schematics/gerbers/BOM

**Comment by tkuester** [comment]
I think this is a good decision -- especially for the firmware, which will change much faster than the hardware. At least for maintaining tags, there may be several revisions of firmware per revision of hardware.

There may be some small utility in tracking the case design and PCB files all within one repository, such as keeping all the hardware issues in one place. If we wish to do things more incrementally (than all at once), perhaps it would be best to start with just two repositories: the firmware and hardware? This may be a little easier for other members in the project to track.
