### ISSUE TITLE
Buttons on the HMI are not aligned properly

### ISSUE THREAD

**Issue by sp5wwp** [sp5wwp/TR-9#18]
Center-align all buttons below the display (and the display itself).

**Comment by tkuester** [comment]
![new](https://user-images.githubusercontent.com/6379955/99686519-a8582a80-2a51-11eb-89f1-502a561ff4d5.png)
![old](https://user-images.githubusercontent.com/6379955/99686521-a8582a80-2a51-11eb-87da-dc0fc052be58.png)

**Comment by tkuester** [comment]
It seems that there are 6 buttons on top for directional / control. Perhaps we want to add a few mm to the 0-9 keypad? Would not be terribly difficult.

Additionally, while the buttons are centered to the display and FPC cutout (I tried to disturb this as little as possible), they are offset to one side on the PCB. Same with the mounting holes. I decided to leave that for another day, but I indicated center lines on the PCB to help with that down the road.
