### ISSUE TITLE
Adopt USB-C

### ISSUE THREAD

**Issue by ghost** [sp5wwp/TR-9#22]
Should we add USB Type C as a connector?

Pros: 

- USB A and B is deprecated
- USB-C is more durable

**Comment by engammar** [comment]
USB c would general standard

**Comment by ghost** [comment]
USB micro-B female to USB-C male adapters are easy to find. I recommend USB-C as more modern, durable, reversible, and also, allowing more current to the battery and/or PA.

Also, USB-C allows host mode more easily (for usb key, etc).

**Comment by sp5wwp** [comment]
We can change it in the next revision, but I have no idea when that's going to happen :-)

**Comment by tkuester** [comment]
As a note, for future me!

When using USB-C, don't forget the CC resistors! That burned me on a recent design.
